version: '3.1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 9094
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      # setup :9092 for access inside the docker network, 9094 for outside (ie host)
      - KAFKA_LISTENERS=INTERNAL://kafka:9094,OUTSIDE://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9094,OUTSIDE://localhost:9092
      # disable encoding of messages (for testing)
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  rooms:
    image: kafka-tutorial/rooms:latest
    ports:
      - "8441:8441"
  sensors:
    image: kafka-tutorial/sensors:latest
    ports:
      - "8440:8440"
    environment:
      TUTORIAL_ROOMSENSORS_URL: http://room-sensors:8442
  room-sensors:
    image: kafka-tutorial/room-sensors:latest
    ports:
      - "8442:8442"
    environment:
      TUTORIAL_EVALUATION_URL: http://evaluation:8443
  evaluation:
    image: kafka-tutorial/evaluation:latest
    ports:
      - "8443:8443"
    environment:
      TUTORIAL_ROOMSENSORS_URL: http://room-sensors:8442
      TUTORIAL_ROOM_SERVICE_URL: http://rooms:8441
